# Generated by Django 4.0.5 on 2022-07-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='validating',
            fields=[
                ('Vid', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('Vname', models.CharField(max_length=100)),
            ],
        ),
    ]
